services:
  citus_coordinator:
    image: citusdata/citus:11.2
    container_name: citus_coordinator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: historia_clinica
    command: ["docker-entrypoint.sh", "postgres", "-c", "wal_level=logical"]
    volumes:
      - coordinator_data:/var/lib/postgresql/data
      - ./schema_citus.sql:/mnt/schema_citus.sql
      - ./insert_datos.sql:/mnt/insert_datos.sql
    networks:
      - citus_net

  citus_worker1:
    image: citusdata/citus:11.2
    container_name: citus_worker1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: historia_clinica
    command: ["docker-entrypoint.sh", "postgres", "-c", "wal_level=logical"]
    volumes:
      - worker1_data:/var/lib/postgresql/data
    networks:
      - citus_net

  citus_worker2:
    image: citusdata/citus:11.2
    container_name: citus_worker2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: historia_clinica
    command: ["docker-entrypoint.sh", "postgres", "-c", "wal_level=logical"]
    volumes:
      - worker2_data:/var/lib/postgresql/data
    networks:
      - citus_net

volumes:
  coordinator_data:
  worker1_data:
  worker2_data:

networks:
  citus_net:
    driver: bridge
